Chore/ch116 Architecture CSS + JS
idesys-dev/idesys-erp pull request #6
Opened 2020-07-20 11:05 UTC by BilelJegham

Ajout de gulp

2020-07-20 11:36 UTC, UlysseGuyon requested changes
ça serait bien d'avoir un README.md dans /template/assets ou alors juste un commentaire de PR pour décrire ce que va faire gulp ici, ou si il y a des trucs à savoir sur son utilisation qui peuvent impacter le développement. Et aussi des descriptions sur les autres changements pourraient être utiles.

2020-07-20 15:39 UTC, BilelJegham commented
Bien vu @UlysseGuyon, je voulais en faire une mais j'ai un peu zappé la voici.
https://github.com/idesys-dev/idesys-erp/wiki/Templates-:-CSS-&-JS

2020-07-20 20:27 UTC, UlysseGuyon approved these changes

2020-07-21 09:01 UTC, Thykof approved these changes

2020-07-21 09:01 UTC, merged